<?xml version="1.0"?>
<robot name="bluerov2" xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
  <!-- Define configurable arguments -->
  <xacro:arg name="namespace" default="bluerov2"/>
  <xacro:arg name="simulation" default="true"/> <!-- Used to conditionally add simulation-related plugins -->
  <xacro:arg name="density" default="1000"/> <!-- Fluid density, e.g., water -->

  <!-- Internal xacro properties based on arguments -->
  <xacro:property name="ns" value="$(arg namespace)"/>
  <xacro:property name="density" value="$(arg density)"/>

  <!-- Main body dimensions -->
  <xacro:property name="x_size" value="0.40"/>
  <xacro:property name="y_size" value="0.25"/>
  <xacro:property name="z_size" value="0.1"/>

  <!-- Main body mass -->
  <xacro:property name="mass" value="14.8"/>
      
  <!-- Mass of a single propeller -->
  <xacro:property name="prop_mass" value="0.07"/>
  
  <!-- Compute volume correction factor to ensure slight positive buoyancy (1% above neutral) -->
  <xacro:property name="buoyant_correction" value="${1.01*pow((mass + 6*prop_mass)/(density*x_size*y_size*z_size), 1./3)}"/>

  <!-- Center of Buoyancy (Z-axis offset) -->
  <xacro:property name="z_cob" value="${-buoyant_correction*z_size/4}"/>

  <!-- Center of Gravity (Z-axis offset) -->
  <xacro:property name="z_cog" value="${-buoyant_correction*z_size}"/>
  
  <!-- Mesh file paths -->
  <xacro:property name="visual_mesh_file" value="package://bluerov2_description/meshes/bluerov2_noprop.dae"/>
  <xacro:property name="collision_mesh_file" value="package://bluerov2_description/meshes/bluerov2_noprop.stl"/>

  <!-- Define the main body link -->
  <link name="${ns}/base_link">

    <!-- Inertial properties for physics simulation -->
    <inertial>
        <mass value="${mass}"/>
        <origin xyz="0 0 ${z_cog}"/> <!-- Set origin at center of gravity -->

        <!-- Inertia matrix from literature (commented default version replaced) -->
        <!-- Reference: Master thesis on MPC for BlueROV2 -->
        <inertia ixx="5.2539" ixy="0.0144" ixz="0.3341" iyy="7.9420" iyz="0.026" izz="6.9123"/>

        <!-- Optional simpler rectangular box inertia model (commented out) -->
<!--
        <inertia
          ixx="${mass/12*(y_size*y_size+z_size*z_size)}" ixy="0.0" ixz="0.0"
          iyy="${mass/12*(x_size*x_size + z_size*z_size)}" iyz="0.0"
          izz="${mass/12*(x_size*x_size + y_size*y_size)}" />
-->
    </inertial>

    <!-- Visual appearance -->
    <visual>
        <geometry>
            <mesh filename="${visual_mesh_file}"/>
        </geometry>
    </visual>
    
    <!-- Collision geometry, used for physics and buoyancy -->
    <collision>
        <origin xyz="0 0 ${z_cob}"/> <!-- Apply CoB offset -->
        <geometry>
            <!-- Simplified box geometry scaled with buoyant correction -->
            <box size="${x_size*buoyant_correction} ${y_size*buoyant_correction} ${z_size*buoyant_correction}"/>
        </geometry>
    </collision>

    <!-- Optional Gazebo parameters (commented out for now) -->
<!--
    <gazebo>
        <velocity_decay>
            <linear>-250.15 -70.364 -170.955</linear>
            <angular>1.888 0.761 3.744</angular>
        </velocity_decay>
    </gazebo>
-->
  </link>
  
  <!-- Include submodules for dynamics, thrusters and sensors -->
  <xacro:include filename="hydrodynamics.xacro"/>
  <xacro:include filename="thrusters.xacro"/>
  <!-- <xacro:include filename="sensors.xacro"/> -->

  <!-- Only include Gazebo plugins if simulation argument is true -->
  <xacro:if value="$(arg simulation)">
    <gazebo>

      <!-- Publishes joint states of the robot -->
      <plugin filename="ignition-gazebo-joint-state-publisher-system" name="ignition::gazebo::systems::JointStatePublisher"/>

      <!-- Publishes odometry from base_link in world frame -->
      <plugin
          filename="ignition-gazebo-odometry-publisher-system"
          name="ignition::gazebo::systems::OdometryPublisher">
          <odom_frame>world</odom_frame>
          <dimensions>3</dimensions>
          <robot_base_frame>${ns}/base_link</robot_base_frame>
          <odom_publish_frequency>20</odom_publish_frequency>
      </plugin>
        
      <!-- Publishes poses of models and links -->
      <plugin
          filename="ignition-gazebo-pose-publisher-system"
          name="ignition::gazebo::systems::PosePublisher">
          <publish_link_pose>false</publish_link_pose>
          <publish_collision_pose>false</publish_collision_pose>
          <publish_visual_pose>false</publish_visual_pose>
          <publish_nested_model_pose>true</publish_nested_model_pose>
      </plugin>

    </gazebo>
  </xacro:if>

</robot>
